# Default values for gatekeeper-constraints
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

limits:
  cpu: 1
  memory: 1024Mi

requests:
  cpu: 1
  memory: 1024Mi
