apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: agc-required-labels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    - airbyte
    - cattle-system
    - external-dns
    - gatekeeper-system
    - ingress-nginx
    - kube-system
    - prometheus
    - velero
    - zabbix
  parameters:
    labels: ["project_code"]
